### PR TITLE
Add `accounts_2` and `merkle-root` json files for `Mainnet` migration

### LINKED ISSUE #143: Prepare `merkle-root.json` and `accounts_2.json` for Mainnet migration
### Description

To be able to execute script [4_deployClaimContract.sh](https://github.com/LiskHQ/lisk-contracts-private/blob/main/script/4_deployClaimContract.sh) for Lisk Mainnet migration, `merkle-root.json` and `accounts_2.json` files needs to be filled in with correct data.

### Acceptance Criteria

There exist `merkle-root.json` and `accounts_2.json` files for Lisk Mainnet migration inside [script/data/mainnet](https://github.com/LiskHQ/lisk-contracts-private/tree/main/script/data/mainnet) folder.

### PR DESCRIPTION
**Pull request by matjazv**
### What was the problem?

This PR resolves #143.

### How was it solved?

`merkle-root.json` and `accounts_2.json` files were added inside [script/data/mainnet](https://github.com/LiskHQ/lisk-contracts-private/tree/main/script/data/mainnet) folder.

### CODE REVIEW

**Review by AndreasKendziorra — APPROVED** [review]
I compared it against the output of 4 scripts.

**Review by shuse2 — APPROVED** [review]

**Review by nagdahimanshu — APPROVED** [review]
LGTM 👍

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍

**Review by ishantiw — APPROVED** [review]

**Review by janhack — APPROVED** [review]
Looks good!

**Pull request merged**
